export const BACKEND_HOST = "http://localhost:3000"
export const BACKEND_HOST_TESTNET = "http://localhost:3001"
export const GRAPHQL_HOST = "http://localhost:8080/v1/graphql"
export const GRAPHQL_HOST_TESTNET = "http://localhost:8081/v1/graphql"
export const TXQ_HOST = "http://localhost:8097/api/v1"
export const TXQ_HOST_TESTNET = "http://localhost:8098/api/v1"
